[shell]
args = ['--login']
program = "/usr/bin/zsh"

[cursor]
style = "Beam"



[window]
dynamic_title = true
opacity = 0.9
startup_mode = "Windowed"
# "Full" | "None" | "Transparent" | "Buttonless"

decorations = "None" 

[window.padding]

x = 10
y = 10

[colors.primary]
background = "#000000"
foreground = "#FFFFFF"

[colors.bright]
black = "#666666"
red = "#FF6666"
green = "#66FF66"
yellow = "#FFFF66"
blue = "#6666FF"
magenta = "#FF66FF"
cyan = "#66FFFF"
white = "#FFFFFF"

[colors.normal]
 black = "#000000"
red = "#FF3333"
green = "#33FF33"
yellow = "#FFFF33"
blue = "#3333FF"
magenta = "#FF33FF"
cyan = "#33FFFF"
white = "#FFFFFF"

[colors.cursor]
#text = "CellBackground"
#cursor = "CellForeground"
text = "#FFFFFF"
cursor = "#FFFFFF"

[env]
LANG = "en_US.UTF-8"
LC_CTYPE = "en_US.UTF-8"
TERM = "alacritty"

[font]
size = 12.0

[font.normal]
family = "FiraCode Nerd Font"
style = "SemiBold"

